# This workflow uploads a Python Package to Test PyPI and GitHub Packages when a test release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

name: Release to Test PyPI and GitHub Packages

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    # Only run on releases with 'alpha' in the tag name
    if: contains(github.event.release.tag_name, 'alpha')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build package for test distribution
        run: |
          python -m pip install build setuptools wheel
          # Clean any previous builds
          rm -rf dist/ build/ *.egg-info/
          python -m build
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists 
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    # Only run if the build job ran (i.e., alpha release)
    if: contains(github.event.release.tag_name, 'alpha')
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    # Use test-release environment for Test PyPI
    environment:
      name: test-release
      # Test PyPI project URL
      url: https://test.pypi.org/project/ada-verona/

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          # Specify Test PyPI repository
          repository-url: https://test.pypi.org/legacy/

  github-packages-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    # Only run if the build job ran (i.e., alpha release)
    if: contains(github.event.release.tag_name, 'alpha')
    permissions:
      contents: read
      packages: write  

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish to GitHub Packages
        # GitHub Packages for Python uses the GitHub API endpoint
        # The package will be available at: https://github.com/henba1/VERONA/packages
        run: |
          python -m pip install twine
          twine upload --repository-url https://api.github.com/repos/henba1/VERONA/packages/pypi dist/*
        env:
          TWINE_USERNAME: ${{ github.actor }}
          TWINE_PASSWORD: ${{ secrets.PACKAGES_TOKEN }}
          TWINE_REPOSITORY_URL: https://api.github.com/repos/henba1/VERONA/packages/pypi